### ISSUE TITLE
Create batch tool 

### ISSUE THREAD

**Issue by dabrhe** [nickworonekin/tppk-tool#2]
Whenever I try to create a .tppk file from one of the puyo_aqua.dat type files it gives me a "Could not get the texture id for 'puyo_aqua.dat'. The texture id is retrieved from the characters after the last underscore in the filename."

**Comment by nickworonekin** [comment]
TppkTool is meant to be used on either tppk archives or files previously extracted from a tppk archive. puyo_aqua.dat and the rest of the puyo_*.dat files are dds textures and shouldn't be used with TppkTool.

**Comment by dabrhe** [comment]
Ah whoops, that makes sense. Thank you.
